name: Deployment - Reusable Workflow

on:
  workflow_call:
    inputs:
      mongodb-uri:
        description: MongoDB connection string
        required: true
        type: string
      kubectl-version:
        description: kubectl CLI version
        required: false
        default: v1.26.0
        type: string
      k8s-manifest-dir:
        description: Path to Kubernetes manifests
        required: true
        default: kubernetes/
        type: string
      environment:
        description: Deployment environment name
        required: true
        default: dev
        type: string
    secrets:
      k8s-kubeconfig:
        required: false
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set lower case repository name
        run: |
          echo "IMAGE_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Install Kubernetes Cluster
        uses: helm/kind-action@v1

      - name: Replace Tokens in Manifests
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{_'
          tokenSuffix: '_}'
          files: "${{ inputs.k8s-manifest-dir }}*.yaml"
        env:
          NAMESPACE: ${{ inputs.environment }}
          REPLICAS: "2"
          IMAGE: ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
          INGRESS_IP: 127.0.0.1

      - name: Create MongoDB Secret
        run: |
          kubectl create namespace ${{ inputs.environment }} || true
          kubectl -n ${{ inputs.environment }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI='${{ inputs.mongodb-uri }}' \
            --from-literal=MONGO_USERNAME='${{ vars.MONGO_USERNAME }}' \
            --from-literal=MONGO_PASSWORD='${{ secrets.mongodb-password }}' \
            --save-config \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Target Environment
        run: kubectl apply -f "${{ inputs.k8s-manifest-dir }}"